# CMake generated Testfile for 
# Source directory: /mds-sfm/pipelines/opencv-2.4.11/modules
# Build directory: /mds-sfm/pipelines/opencv-2.4.11/release/modules
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs(androidcamera/.androidcamera)
subdirs(calib3d/.calib3d)
subdirs(contrib/.contrib)
subdirs(core/.core)
subdirs(dynamicuda/.dynamicuda)
subdirs(features2d/.features2d)
subdirs(flann/.flann)
subdirs(gpu/.gpu)
subdirs(highgui/.highgui)
subdirs(imgproc/.imgproc)
subdirs(java/.java)
subdirs(legacy/.legacy)
subdirs(ml/.ml)
subdirs(nonfree/.nonfree)
subdirs(objdetect/.objdetect)
subdirs(ocl/.ocl)
subdirs(photo/.photo)
subdirs(python/.python)
subdirs(stitching/.stitching)
subdirs(superres/.superres)
subdirs(ts/.ts)
subdirs(video/.video)
subdirs(videostab/.videostab)
subdirs(viz/.viz)
subdirs(world/.world)
subdirs(core)
subdirs(flann)
subdirs(imgproc)
subdirs(highgui)
subdirs(features2d)
subdirs(calib3d)
subdirs(ml)
subdirs(video)
subdirs(legacy)
subdirs(objdetect)
subdirs(photo)
subdirs(gpu)
subdirs(ocl)
subdirs(nonfree)
subdirs(contrib)
subdirs(python)
subdirs(stitching)
subdirs(superres)
subdirs(ts)
subdirs(videostab)
